<?php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(200); exit(); }
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Method not allowed']);
    exit();
}

// ── Input validation ─────────────────────────────────────────────────────────
$input  = json_decode(file_get_contents('php://input'), true);
$rawUrl = trim($input['url'] ?? '');

if (empty($rawUrl)) {
    http_response_code(400);
    echo json_encode(['error' => 'No URL provided']);
    exit();
}

if (!preg_match('#^https?://#i', $rawUrl)) {
    $rawUrl = 'https://' . $rawUrl;
}

if (!filter_var($rawUrl, FILTER_VALIDATE_URL)) {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid URL']);
    exit();
}

$host = parse_url($rawUrl, PHP_URL_HOST);
$ip   = gethostbyname($host);
if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) === false) {
    http_response_code(403);
    echo json_encode(['error' => 'Private or reserved IP addresses are not allowed']);
    exit();
}

// ── Fetch HTML ───────────────────────────────────────────────────────────────
function fetchHtml(string $url): string
{
    $ch = curl_init();
    curl_setopt_array($ch, [
        CURLOPT_URL            => $url,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_MAXREDIRS      => 5,
        CURLOPT_TIMEOUT        => 10,
        CURLOPT_USERAGENT      => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        CURLOPT_HTTPHEADER     => ['Accept: text/html,application/xhtml+xml'],
        CURLOPT_SSL_VERIFYPEER => true,
        CURLOPT_ENCODING       => 'gzip, deflate',
    ]);
    $html  = curl_exec($ch);
    $error = curl_error($ch);
    curl_close($ch);

    if ($html === false) throw new RuntimeException('Fetch failed: ' . $error);
    return mb_substr($html, 0, 500000);
}

// ══════════════════════════════════════════════════════════════════════════════
// SIGNAL LIBRARIES
// ══════════════════════════════════════════════════════════════════════════════

// ── 1. AI / vibe-coded marketing buzzwords ───────────────────────────────────
$AI_PHRASES = [
    // Classic buzzwords
    'leverage', 'synergy', 'streamline', 'scalable', 'robust', 'seamless',
    'cutting-edge', 'state-of-the-art', 'innovative', 'comprehensive',
    'holistic', 'empower', 'transformative', 'dynamic', 'strategic',
    'game-changer', 'disruptive', 'bespoke', 'tailored solutions',
    'unlock your potential', 'take your business to the next level',
    'best-in-class', 'world-class', 'industry-leading', 'next-generation',
    'end-to-end', 'value-added', 'thought leader', 'paradigm shift',
    'actionable insights', 'move the needle', 'bleeding edge',
    'mission-critical', 'pain points', 'deep dive', 'low-hanging fruit',
    'future-proof', 'lorem ipsum',
    // Modern AI / vibe-coded landing page staples
    'boost your', 'supercharge', 'revolutionize', 'harness the power',
    'elevate your', 'optimize your', 'maximize your', 'skyrocket',
    'effortlessly', 'powerful yet simple', 'simple yet powerful',
    'say goodbye to', 'say hello to', 'meet your new', 'introducing',
    'built for', 'designed for modern', 'designed for teams',
    'all-in-one', 'everything you need', 'loved by thousands',
    'join thousands', 'join hundreds', 'trusted by', 'used by',
    'start for free', 'free forever', 'no credit card required',
    'get started today', 'start your journey', 'your dream',
    'the future of', 'reimagined', 'rethought', 'reinvented',
    'powered by ai', 'ai-powered', 'built with ai', 'ai-generated',
    'chatgpt', 'generated by', 'crafted by ai', 'written by ai',
    'beautiful', 'stunning', 'delightful', 'intuitive interface',
    'blazing fast', 'lightning fast', 'instant results',
    'one platform', 'one tool', 'one solution',
];

// ── 2. Site builder / generator signatures ───────────────────────────────────
$BUILDER_SIGNATURES = [
    'wix.com'           => 'Wix',
    'wixstatic'         => 'Wix',
    'squarespace.com'   => 'Squarespace',
    'squarespace'       => 'Squarespace',
    'webflow.com'       => 'Webflow',
    'webflow-io'        => 'Webflow',
    'webflow'           => 'Webflow',
    'wordpress'         => 'WordPress',
    'wp-content'        => 'WordPress',
    'wp-includes'       => 'WordPress',
    'shopify'           => 'Shopify',
    'myshopify'         => 'Shopify',
    'weebly'            => 'Weebly',
    'godaddy'           => 'GoDaddy',
    'elementor'         => 'Elementor',
    'et_pb'             => 'Divi',
    'framer.com'        => 'Framer',
    'framerusercontent' => 'Framer',
    'carrd.co'          => 'Carrd',
    'site123'           => 'Site123',
    'bubble.io'         => 'Bubble',
    'webnode'           => 'Webnode',
    'strikingly'        => 'Strikingly',
    'tilda'             => 'Tilda',
    'notion.site'       => 'Notion',
    'super.so'          => 'Super.so',
];

// ── 3. Tailwind utility class patterns (massive vibe-code signal) ─────────────
$TAILWIND_UTILITY_PATTERNS = [
    // Layout combos AI loves
    'flex items-center justify-between',
    'flex items-center justify-center',
    'flex flex-col items-center',
    'grid grid-cols-',
    'mx-auto max-w-',
    'px-4 py-',
    'w-full max-w-',
    // Spacing patterns
    'space-y-4', 'space-y-6', 'space-y-8',
    'space-x-4', 'space-x-6',
    'gap-4', 'gap-6', 'gap-8',
    // Typography combos
    'text-4xl font-bold', 'text-3xl font-bold', 'text-2xl font-bold',
    'text-xl font-semibold', 'text-lg font-medium',
    'font-bold text-', 'font-semibold text-',
    // Colour patterns AI defaults to
    'bg-blue-600', 'bg-blue-500', 'bg-indigo-600',
    'text-gray-600', 'text-gray-700', 'text-gray-900',
    'hover:bg-blue-700', 'hover:bg-blue-600',
    // Rounded / shadow combos
    'rounded-lg shadow', 'rounded-xl shadow',
    'rounded-full', 'shadow-lg', 'shadow-xl',
    // Container patterns
    'container mx-auto', 'max-w-7xl mx-auto', 'max-w-6xl mx-auto',
    'max-w-4xl mx-auto', 'max-w-3xl mx-auto',
    // Section padding AI always adds
    'py-16', 'py-20', 'py-24',
    // Responsive grid AI loves
    'md:grid-cols-2', 'md:grid-cols-3', 'lg:grid-cols-3',
    'sm:grid-cols-2', 'lg:grid-cols-4',
    // Transition boilerplate
    'transition-all duration-', 'transition duration-',
    'hover:scale-', 'hover:shadow-',
];

// ── 4. AI HTML comment patterns (LLMs scaffold code with section labels) ──────
$AI_COMMENT_PATTERNS = [
    '<!-- hero',
    '<!-- navigation',
    '<!-- navbar',
    '<!-- features',
    '<!-- benefits',
    '<!-- how it works',
    '<!-- testimonials',
    '<!-- pricing',
    '<!-- cta',
    '<!-- call to action',
    '<!-- footer',
    '<!-- about',
    '<!-- faq',
    '<!-- contact',
    '<!-- stats',
    '<!-- team',
    '<!-- newsletter',
    '<!-- main content',
    '<!-- header section',
    '<!-- services',
];

// ── 5. Predictable AI landing page section IDs / classes ─────────────────────
$AI_SECTION_PATTERNS = [
    'id="hero"', 'id="features"', 'id="pricing"',
    'id="testimonials"', 'id="cta"', 'id="about"',
    'id="how-it-works"', 'id="faq"', 'id="contact"',
    'id="benefits"', 'id="stats"', 'id="team"',
    'class="hero"', 'class="features"', 'class="pricing"',
    'class="testimonials"', 'class="cta"',
    'class="hero-section"', 'class="features-section"',
    'class="pricing-section"', 'class="cta-section"',
    // shadcn / Radix (common in vibe-coded React)
    'data-radix-',
    'class="card-content"', 'class="card-header"', 'class="card-title"',
    'class="card-description"', 'class="badge"',
];

// ══════════════════════════════════════════════════════════════════════════════
// ANALYSIS ENGINE
// ══════════════════════════════════════════════════════════════════════════════
function analyzeHtml(
    string $html,
    array $AI_PHRASES,
    array $BUILDER_SIGNATURES,
    array $TAILWIND_UTILITY_PATTERNS,
    array $AI_COMMENT_PATTERNS,
    array $AI_SECTION_PATTERNS
): array {
    $lower   = strtolower($html);
    $score   = 0;
    $reasons = [];

    // ── A. Builder / generator signatures ────────────────────────────────────
    $detectedBuilders = [];
    foreach ($BUILDER_SIGNATURES as $sig => $label) {
        if (str_contains($lower, $sig) && !in_array($label, $detectedBuilders)) {
            $detectedBuilders[] = $label;
        }
    }
    preg_match_all('/<meta[^>]+name=["\']generator["\'][^>]*content=["\']([^"\']+)["\'][^>]*>/i', $html, $m1);
    preg_match_all('/<meta[^>]+content=["\']([^"\']+)["\'][^>]*name=["\']generator["\'][^>]*>/i', $html, $m2);
    $generatorValues = array_merge($m1[1] ?? [], $m2[1] ?? []);

    if (!empty($detectedBuilders)) {
        $score += min(count($detectedBuilders) * 18, 35);
        $reasons[] = 'Site builder detected: ' . implode(', ', $detectedBuilders) . ' — these tools produce template-driven, often AI-assisted content';
    }
    if (!empty($generatorValues)) {
        $score += 12;
        $gen = htmlspecialchars(trim($generatorValues[0]));
        $reasons[] = "Meta generator tag: \"$gen\"";
    }

    // ── B. Tailwind utility class density ────────────────────────────────────
    $tailwindHits = 0;
    foreach ($TAILWIND_UTILITY_PATTERNS as $pattern) {
        if (str_contains($lower, strtolower($pattern))) $tailwindHits++;
    }

    preg_match_all('/class=["\']([^"\']+)["\']/', $html, $classAttr);
    $allClasses   = [];
    $longClassStr = 0;
    foreach ($classAttr[1] as $classStr) {
        $parts = array_filter(preg_split('/\s+/', trim($classStr)));
        $allClasses = array_merge($allClasses, array_values($parts));
        if (count($parts) >= 8) $longClassStr++;
    }

    $twPrefixes = ['flex','grid','text-','bg-','px-','py-','p-','mx-','my-','mt-','mb-','ml-','mr-','w-','h-','max-w-','min-h-','rounded','shadow','border','font-','items-','justify-','gap-','space-','hover:','md:','lg:','sm:','xl:','2xl:','transition','duration-','opacity-','z-','absolute','relative','fixed','overflow','cursor-','pointer-','col-','row-','self-','place-','inset-','top-','bottom-','left-','right-','ring-'];
    $twClassCount = 0;
    foreach ($allClasses as $cls) {
        foreach ($twPrefixes as $prefix) {
            if (str_starts_with($cls, $prefix)) { $twClassCount++; break; }
        }
    }
    $totalClasses  = count($allClasses);
    $tailwindRatio = $totalClasses > 10 ? $twClassCount / $totalClasses : 0;

    if ($tailwindRatio > 0.55 || $tailwindHits >= 8) {
        $score += 25;
        $reasons[] = sprintf(
            'Heavy Tailwind CSS detected (%.0f%% utility classes, %d AI-typical combos) — the #1 fingerprint of vibe-coded output',
            $tailwindRatio * 100, $tailwindHits
        );
    } elseif ($tailwindRatio > 0.35 || $tailwindHits >= 4) {
        $score += 14;
        $reasons[] = sprintf(
            'Significant Tailwind usage (%.0f%% utility classes) — commonly used in AI-generated sites',
            $tailwindRatio * 100
        );
    }

    if ($longClassStr >= 5) {
        $score += 10;
        $reasons[] = "$longClassStr elements carry 8+ stacked utility classes — characteristic of AI-generated Tailwind markup";
    }

    // ── C. AI HTML comment patterns ──────────────────────────────────────────
    $commentHits   = 0;
    $commentSample = [];
    foreach ($AI_COMMENT_PATTERNS as $pattern) {
        if (str_contains($lower, strtolower($pattern))) {
            $commentHits++;
            if (count($commentSample) < 2) $commentSample[] = ltrim(trim($pattern), '<!- ');
        }
    }
    if ($commentHits >= 4) {
        $score += 20;
        $reasons[] = "$commentHits section-label HTML comments (\"" . implode('", "', $commentSample) . "\"…) — LLMs almost always scaffold code with these labels";
    } elseif ($commentHits >= 2) {
        $score += 10;
        $reasons[] = "$commentHits structural HTML comments detected — suggests LLM-scaffolded page layout";
    }

    // ── D. Cookie-cutter section IDs / classes ───────────────────────────────
    $sectionHits = 0;
    foreach ($AI_SECTION_PATTERNS as $pattern) {
        if (str_contains($lower, strtolower($pattern))) $sectionHits++;
    }
    if ($sectionHits >= 5) {
        $score += 18;
        $reasons[] = "$sectionHits cookie-cutter section IDs/classes found — AI generates the same hero → features → pricing → CTA structure every time";
    } elseif ($sectionHits >= 3) {
        $score += 10;
        $reasons[] = "$sectionHits standard landing page sections detected — the textbook AI site structure";
    }

    // ── E. Marketing buzzword density ────────────────────────────────────────
    $foundPhrases = [];
    foreach ($AI_PHRASES as $phrase) {
        if (str_contains($lower, $phrase)) $foundPhrases[] = $phrase;
    }
    $phraseCount = count($foundPhrases);
    $score += min($phraseCount * 3, 25);

    if ($phraseCount >= 8) {
        $examples = array_slice($foundPhrases, 0, 3);
        $reasons[] = "$phraseCount buzzwords found (\"" . implode('", "', $examples) . "\"…) — saturated with AI copywriting";
    } elseif ($phraseCount >= 4) {
        $examples = array_slice($foundPhrases, 0, 2);
        $reasons[] = "$phraseCount marketing buzzwords detected (\"" . implode('", "', $examples) . "\") — typical AI copy patterns";
    } elseif ($phraseCount >= 1) {
        $reasons[] = "Minor buzzword usage (\"$foundPhrases[0]\") — weak but present AI copy signal";
    }

    // ── F. Inline style overuse ───────────────────────────────────────────────
    preg_match_all('/\bstyle=["\'][^"\']{20,}["\']/', $html, $inlineStyles);
    $inlineCount = count($inlineStyles[0]);
    if ($inlineCount > 25) {
        $score += 10;
        $reasons[] = "$inlineCount inline style attributes — AI often mixes Tailwind with inline styles";
    } elseif ($inlineCount > 10) {
        $score += 5;
    }

    // ── G. Sentence length uniformity ────────────────────────────────────────
    $textOnly  = preg_replace('/<[^>]+>/', ' ', $html);
    $textOnly  = html_entity_decode(preg_replace('/\s+/', ' ', $textOnly), ENT_QUOTES, 'UTF-8');
    $sentences = preg_split('/[.!?]+/', $textOnly);
    $sentences = array_values(array_filter($sentences, fn($s) => str_word_count(trim($s)) >= 5 && str_word_count(trim($s)) <= 60));

    if (count($sentences) >= 10) {
        $lengths  = array_map(fn($s) => str_word_count(trim($s)), $sentences);
        $avg      = array_sum($lengths) / count($lengths);
        $variance = array_sum(array_map(fn($l) => ($l - $avg) ** 2, $lengths)) / count($lengths);

        if ($variance < 8) {
            $score += 15;
            $reasons[] = sprintf('Unnaturally uniform sentence structure (variance %.1f) — AI prose tends to be metronomically consistent', $variance);
        } elseif ($variance < 15) {
            $score += 7;
        } elseif ($variance > 90) {
            $score -= 8;
            $reasons[] = sprintf('High natural sentence rhythm variation (variance %.1f) — more consistent with human writing', $variance);
        }
    }

    // ── H. CSS class repetition ───────────────────────────────────────────────
    $uniqueClasses = count(array_count_values($allClasses));
    if ($totalClasses > 20) {
        $repetitionRatio = ($totalClasses - $uniqueClasses) / $totalClasses;
        $repPct          = round($repetitionRatio * 100);

        if ($repetitionRatio > 0.75) {
            $score += 15;
            $reasons[] = "Extreme CSS class repetition ($repPct% reused) — strongly suggests auto-generated template markup";
        } elseif ($repetitionRatio > 0.55) {
            $score += 8;
        } elseif ($repetitionRatio < 0.18 && $uniqueClasses > 40) {
            $score -= 8;
            $reasons[] = "Diverse CSS class naming ($uniqueClasses unique classes) — suggests hand-crafted styles";
        }
    }

    // ── I. Script tag overload ────────────────────────────────────────────────
    preg_match_all('/<script\b[^>]*>/i', $html, $scriptTags);
    $scriptCount = count($scriptTags[0]);
    if ($scriptCount > 25) {
        $score += 8;
        $reasons[] = "$scriptCount script tags — heavy JS injection typical of builder-generated SPAs";
    }

    // ── J. Heading keyword stuffing ───────────────────────────────────────────
    preg_match_all('/<h[1-6][^>]*>(.*?)<\/h[1-6]>/is', $html, $headingMatches);
    $headingText  = strtolower(strip_tags(implode(' ', $headingMatches[1] ?? [])));
    $headingWords = array_filter(preg_split('/\s+/', $headingText), fn($w) => strlen($w) > 3);
    if (count($headingWords) > 5) {
        $wordCounts = array_count_values($headingWords);
        arsort($wordCounts);
        $topCount = reset($wordCounts);
        $topWord  = key($wordCounts);
        if ($topCount >= 3) {
            $score += 8;
            $reasons[] = "Heading keyword stuffing: \"$topWord\" repeated $topCount times — classic AI SEO content";
        }
    }

    // ── Clamp & guarantee minimum reasons ────────────────────────────────────
    $score = max(0, min(100, $score));

    if (count($reasons) < 2) {
        $reasons[] = $score < 35
            ? 'No major AI or builder fingerprints found — reads as organically written'
            : 'Multiple subtle signals collectively suggest automated or template-driven content';
    }

    $reasons = array_slice($reasons, 0, 3);

    // Verdict threshold lowered to 45 to lean toward catching vibe-coded sites
    $verdict = $score >= 45 ? 'Likely AI' : 'Likely Human';

    return compact('score', 'verdict', 'reasons');
}

// ── Execute ───────────────────────────────────────────────────────────────────
try {
    $html   = fetchHtml($rawUrl);
    $result = analyzeHtml($html, $AI_PHRASES, $BUILDER_SIGNATURES, $TAILWIND_UTILITY_PATTERNS, $AI_COMMENT_PATTERNS, $AI_SECTION_PATTERNS);
    echo json_encode($result);
} catch (RuntimeException $e) {
    http_response_code(422);
    echo json_encode(['error' => $e->getMessage()]);
} catch (Throwable $e) {
    http_response_code(500);
    echo json_encode(['error' => 'Internal server error']);
}
