<?php
// ══════════════════════════════════════════════════════════════════════════════
// VIBE CHECKER — unified index.php
// Routes:
//   OPTIONS                  → CORS preflight
//   POST (application/json)  → JSON analysis API  (used by the React fetch)
//   GET                      → Full HTML page
//                              ?url=<encoded>  server-side pre-render + OG tags
// ══════════════════════════════════════════════════════════════════════════════

// ── Signal libraries ──────────────────────────────────────────────────────────
$AI_PHRASES = [
    'leverage','synergy','streamline','scalable','robust','seamless',
    'cutting-edge','state-of-the-art','innovative','comprehensive',
    'holistic','empower','transformative','dynamic','strategic',
    'game-changer','disruptive','bespoke','tailored solutions',
    'unlock your potential','take your business to the next level',
    'best-in-class','world-class','industry-leading','next-generation',
    'end-to-end','value-added','thought leader','paradigm shift',
    'actionable insights','move the needle','bleeding edge',
    'mission-critical','pain points','deep dive','low-hanging fruit',
    'future-proof','lorem ipsum',
    'boost your','supercharge','revolutionize','harness the power',
    'elevate your','optimize your','maximize your','skyrocket',
    'effortlessly','powerful yet simple','simple yet powerful',
    'say goodbye to','say hello to','meet your new','introducing',
    'built for','designed for modern','designed for teams',
    'all-in-one','everything you need','loved by thousands',
    'join thousands','join hundreds','trusted by','used by',
    'start for free','free forever','no credit card required',
    'get started today','start your journey','your dream',
    'the future of','reimagined','rethought','reinvented',
    'powered by ai','ai-powered','built with ai','ai-generated',
    'chatgpt','generated by','crafted by ai','written by ai',
    'beautiful','stunning','delightful','intuitive interface',
    'blazing fast','lightning fast','instant results',
    'one platform','one tool','one solution',
];

$BUILDER_SIGNATURES = [
// === AI-POWERED BUILDERS ===
'lovable.app'=>'Lovable','lovableproject.com'=>'Lovable','gpt-engineer'=>'Lovable',
'base44.app'=>'Base44','base44'=>'Base44',
'bolt.new'=>'Bolt.new','stackblitz'=>'Bolt.new',
'v0.dev'=>'v0 by Vercel','v0-user-next-app'=>'v0 by Vercel',
'replit.com'=>'Replit','repl.co'=>'Replit','replit'=>'Replit',
'cursor.sh'=>'Cursor','cursor-ai'=>'Cursor',
'windsurf'=>'Windsurf','codeium'=>'Windsurf',
'Claude Code'=>'Claude Code','claude-artifact'=>'Claude Code',
'devin.ai'=>'Devin','cognition-labs'=>'Devin',
'val.town'=>'Val.town',
'glitch.me'=>'Glitch','glitch.com'=>'Glitch','cdn.glitch'=>'Glitch',
'gemini-built'=>'Google AI Studio','firebase'=>'Firebase','firebaseapp.com'=>'Firebase','web.app'=>'Firebase',
'idx.google'=>'Google Project IDX','project-idx'=>'Google Project IDX',

// === HOSTING / DEPLOYMENT PLATFORMS (with generator signatures) ===
'netlify.app'=>'Netlify','netlify'=>'Netlify',
'vercel.app'=>'Vercel','_vercel'=>'Vercel',
'github.io'=>'GitHub Pages','github-pages'=>'GitHub Pages',
'pages.dev'=>'Cloudflare Pages','cloudflare-pages'=>'Cloudflare Pages',
'render.com'=>'Render','onrender.com'=>'Render',
'railway.app'=>'Railway',
'fly.dev'=>'Fly.io',

// === CMS / HEADLESS / SITE GENERATORS ===
'gatsby'=>'Gatsby','gatsby-plugin'=>'Gatsby',
'next.js'=>'Next.js','_next/static'=>'Next.js','__NEXT_DATA__'=>'Next.js',
'nuxt'=>'Nuxt.js','__nuxt'=>'Nuxt.js',
'astro'=>'Astro','astro-island'=>'Astro',
'svelte'=>'SvelteKit','__sveltekit'=>'SvelteKit',
'hugo'=>'Hugo','hugo-theme'=>'Hugo',
'jekyll'=>'Jekyll','jekyll-theme'=>'Jekyll',
'11ty'=>'Eleventy','eleventy'=>'Eleventy',
'ghost'=>'Ghost','ghost.io'=>'Ghost',
'contentful'=>'Contentful',
'sanity.io'=>'Sanity',
'strapi'=>'Strapi',
'payload-cms'=>'Payload CMS',

// === UI FRAMEWORKS (detectable via class patterns/scripts) ===
'tailwindcss'=>'Tailwind CSS','tw-'=>'Tailwind CSS',
'bootstrap'=>'Bootstrap','btn-primary'=>'Bootstrap',
'mui'=>'Material UI','MuiBox'=>'Material UI',
'chakra-ui'=>'Chakra UI',
'shadcn'=>'shadcn/ui',
'ant-design'=>'Ant Design','antd'=>'Ant Design',
];

$TAILWIND_UTILITY_PATTERNS = [
    'flex items-center justify-between','flex items-center justify-center',
    'flex flex-col items-center','grid grid-cols-','mx-auto max-w-',
    'px-4 py-','w-full max-w-',
    'space-y-4','space-y-6','space-y-8','space-x-4','space-x-6',
    'gap-4','gap-6','gap-8',
    'text-4xl font-bold','text-3xl font-bold','text-2xl font-bold',
    'text-xl font-semibold','text-lg font-medium',
    'font-bold text-','font-semibold text-',
    'bg-blue-600','bg-blue-500','bg-indigo-600',
    'text-gray-600','text-gray-700','text-gray-900',
    'hover:bg-blue-700','hover:bg-blue-600',
    'rounded-lg shadow','rounded-xl shadow','rounded-full','shadow-lg','shadow-xl',
    'container mx-auto','max-w-7xl mx-auto','max-w-6xl mx-auto',
    'max-w-4xl mx-auto','max-w-3xl mx-auto',
    'py-16','py-20','py-24',
    'md:grid-cols-2','md:grid-cols-3','lg:grid-cols-3',
    'sm:grid-cols-2','lg:grid-cols-4',
    'transition-all duration-','transition duration-',
    'hover:scale-','hover:shadow-',
];

$AI_COMMENT_PATTERNS = [
    '<!-- hero','<!-- navigation','<!-- navbar','<!-- features',
    '<!-- benefits','<!-- how it works','<!-- testimonials',
    '<!-- pricing','<!-- cta','<!-- call to action','<!-- footer',
    '<!-- about','<!-- faq','<!-- contact','<!-- stats','<!-- team',
    '<!-- newsletter','<!-- main content','<!-- header section','<!-- services',
];

$AI_SECTION_PATTERNS = [
    'id="hero"','id="features"','id="pricing"',
    'id="testimonials"','id="cta"','id="about"',
    'id="how-it-works"','id="faq"','id="contact"',
    'id="benefits"','id="stats"','id="team"',
    'class="hero"','class="features"','class="pricing"',
    'class="testimonials"','class="cta"',
    'class="hero-section"','class="features-section"',
    'class="pricing-section"','class="cta-section"',
    'data-radix-',
    'class="card-content"','class="card-header"','class="card-title"',
    'class="card-description"','class="badge"',
];

// ── Fetch HTML ────────────────────────────────────────────────────────────────
function fetchHtml(string $url): string {
    $ch = curl_init();
    curl_setopt_array($ch, [
        CURLOPT_URL            => $url,
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_MAXREDIRS      => 5,
        CURLOPT_TIMEOUT        => 10,
        CURLOPT_USERAGENT      => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        CURLOPT_HTTPHEADER     => ['Accept: text/html,application/xhtml+xml'],
        CURLOPT_SSL_VERIFYPEER => true,
        CURLOPT_ENCODING       => 'gzip, deflate',
    ]);
    $html  = curl_exec($ch);
    $error = curl_error($ch);
    curl_close($ch);
    if ($html === false) throw new RuntimeException('Fetch failed: ' . $error);
    return mb_substr($html, 0, 500000);
}

// ── Analysis Engine ───────────────────────────────────────────────────────────
function analyzeHtml(string $html, array $AI_PHRASES, array $BUILDER_SIGNATURES,
    array $TAILWIND_UTILITY_PATTERNS, array $AI_COMMENT_PATTERNS, array $AI_SECTION_PATTERNS): array
{
    $lower = strtolower($html);
    $score = 0;
    $reasons = [];

    // A. Builder / generator signatures
    $detectedBuilders = [];
    foreach ($BUILDER_SIGNATURES as $sig => $label)
        if (str_contains($lower, $sig) && !in_array($label, $detectedBuilders))
            $detectedBuilders[] = $label;

    preg_match_all('/<meta[^>]+name=["\']generator["\'][^>]*content=["\']([^"\']+)["\'][^>]*>/i', $html, $m1);
    preg_match_all('/<meta[^>]+content=["\']([^"\']+)["\'][^>]*name=["\']generator["\'][^>]*>/i', $html, $m2);
    $generatorValues = array_merge($m1[1] ?? [], $m2[1] ?? []);

    if (!empty($detectedBuilders)) {
        $score += min(count($detectedBuilders) * 18, 35);
        $reasons[] = 'Site builder detected: ' . implode(', ', $detectedBuilders) . ' — these tools produce template-driven, often AI-assisted content';
    }
    if (!empty($generatorValues)) {
        $score += 12;
        $gen = htmlspecialchars(trim($generatorValues[0]));
        $reasons[] = "Meta generator tag: \"$gen\"";
    }

    // B. Tailwind utility class density
    $tailwindHits = 0;
    foreach ($TAILWIND_UTILITY_PATTERNS as $pattern)
        if (str_contains($lower, strtolower($pattern))) $tailwindHits++;

    preg_match_all('/class=["\']([^"\']+)["\']/', $html, $classAttr);
    $allClasses = []; $longClassStr = 0;
    foreach ($classAttr[1] as $classStr) {
        $parts = array_filter(preg_split('/\s+/', trim($classStr)));
        $allClasses = array_merge($allClasses, array_values($parts));
        if (count($parts) >= 8) $longClassStr++;
    }
    $twPrefixes = ['flex','grid','text-','bg-','px-','py-','p-','mx-','my-','mt-','mb-','ml-','mr-','w-','h-','max-w-','min-h-','rounded','shadow','border','font-','items-','justify-','gap-','space-','hover:','md:','lg:','sm:','xl:','2xl:','transition','duration-','opacity-','z-','absolute','relative','fixed','overflow','cursor-','pointer-','col-','row-','self-','place-','inset-','top-','bottom-','left-','right-','ring-'];
    $twClassCount = 0;
    foreach ($allClasses as $cls)
        foreach ($twPrefixes as $prefix)
            if (str_starts_with($cls, $prefix)) { $twClassCount++; break; }

    $totalClasses  = count($allClasses);
    $tailwindRatio = $totalClasses > 10 ? $twClassCount / $totalClasses : 0;

    if ($tailwindRatio > 0.55 || $tailwindHits >= 8) {
        $score += 25;
        $reasons[] = sprintf('Heavy Tailwind CSS detected (%.0f%% utility classes, %d AI-typical combos) — the #1 fingerprint of vibe-coded output', $tailwindRatio * 100, $tailwindHits);
    } elseif ($tailwindRatio > 0.35 || $tailwindHits >= 4) {
        $score += 14;
        $reasons[] = sprintf('Significant Tailwind usage (%.0f%% utility classes) — commonly used in AI-generated sites', $tailwindRatio * 100);
    }
    if ($longClassStr >= 5) {
        $score += 10;
        $reasons[] = "$longClassStr elements carry 8+ stacked utility classes — characteristic of AI-generated Tailwind markup";
    }

    // C. AI HTML comment patterns
    $commentHits = 0; $commentSample = [];
    foreach ($AI_COMMENT_PATTERNS as $pattern) {
        if (str_contains($lower, strtolower($pattern))) {
            $commentHits++;
            if (count($commentSample) < 2) $commentSample[] = ltrim(trim($pattern), '<!- ');
        }
    }
    if ($commentHits >= 4) {
        $score += 20;
        $reasons[] = "$commentHits section-label HTML comments (\"" . implode('", "', $commentSample) . "\"…) — LLMs almost always scaffold code with these labels";
    } elseif ($commentHits >= 2) {
        $score += 10;
        $reasons[] = "$commentHits structural HTML comments detected — suggests LLM-scaffolded page layout";
    }

    // D. Cookie-cutter section IDs / classes
    $sectionHits = 0;
    foreach ($AI_SECTION_PATTERNS as $pattern)
        if (str_contains($lower, strtolower($pattern))) $sectionHits++;
    if ($sectionHits >= 5) {
        $score += 18;
        $reasons[] = "$sectionHits cookie-cutter section IDs/classes found — AI generates the same hero → features → pricing → CTA structure every time";
    } elseif ($sectionHits >= 3) {
        $score += 10;
        $reasons[] = "$sectionHits standard landing page sections detected — the textbook AI site structure";
    }

    // E. Marketing buzzword density
    $foundPhrases = [];
    foreach ($AI_PHRASES as $phrase)
        if (str_contains($lower, $phrase)) $foundPhrases[] = $phrase;
    $phraseCount = count($foundPhrases);
    $score += min($phraseCount * 3, 25);
    if ($phraseCount >= 8) {
        $examples = array_slice($foundPhrases, 0, 3);
        $reasons[] = "$phraseCount buzzwords found (\"" . implode('", "', $examples) . "\"…) — saturated with AI copywriting";
    } elseif ($phraseCount >= 4) {
        $examples = array_slice($foundPhrases, 0, 2);
        $reasons[] = "$phraseCount marketing buzzwords detected (\"" . implode('", "', $examples) . "\") — typical AI copy patterns";
    } elseif ($phraseCount >= 1) {
        $reasons[] = "Minor buzzword usage (\"$foundPhrases[0]\") — weak but present AI copy signal";
    }

    // F. Inline style overuse
    preg_match_all('/\bstyle=["\'][^"\']{20,}["\']/', $html, $inlineStyles);
    $inlineCount = count($inlineStyles[0]);
    if ($inlineCount > 25)      { $score += 10; $reasons[] = "$inlineCount inline style attributes — AI often mixes Tailwind with inline styles"; }
    elseif ($inlineCount > 10)  { $score += 5; }

    // G. Sentence length uniformity
    $textOnly  = preg_replace('/<[^>]+>/', ' ', $html);
    $textOnly  = html_entity_decode(preg_replace('/\s+/', ' ', $textOnly), ENT_QUOTES, 'UTF-8');
    $sentences = preg_split('/[.!?]+/', $textOnly);
    $sentences = array_values(array_filter($sentences, fn($s) => str_word_count(trim($s)) >= 5 && str_word_count(trim($s)) <= 60));
    if (count($sentences) >= 10) {
        $lengths  = array_map(fn($s) => str_word_count(trim($s)), $sentences);
        $avg      = array_sum($lengths) / count($lengths);
        $variance = array_sum(array_map(fn($l) => ($l - $avg) ** 2, $lengths)) / count($lengths);
        if ($variance < 8)       { $score += 15; $reasons[] = sprintf('Unnaturally uniform sentence structure (variance %.1f) — AI prose tends to be metronomically consistent', $variance); }
        elseif ($variance < 15)  { $score += 7; }
        elseif ($variance > 90)  { $score -= 8;  $reasons[] = sprintf('High natural sentence rhythm variation (variance %.1f) — more consistent with human writing', $variance); }
    }

    // H. CSS class repetition
    $uniqueClasses = count(array_count_values($allClasses));
    if ($totalClasses > 20) {
        $repetitionRatio = ($totalClasses - $uniqueClasses) / $totalClasses;
        $repPct = round($repetitionRatio * 100);
        if ($repetitionRatio > 0.75)                          { $score += 15; $reasons[] = "Extreme CSS class repetition ($repPct% reused) — strongly suggests auto-generated template markup"; }
        elseif ($repetitionRatio > 0.55)                      { $score += 8; }
        elseif ($repetitionRatio < 0.18 && $uniqueClasses > 40) { $score -= 8; $reasons[] = "Diverse CSS class naming ($uniqueClasses unique classes) — suggests hand-crafted styles"; }
    }

    // I. Script tag overload
    preg_match_all('/<script\b[^>]*>/i', $html, $scriptTags);
    $scriptCount = count($scriptTags[0]);
    if ($scriptCount > 25) { $score += 8; $reasons[] = "$scriptCount script tags — heavy JS injection typical of builder-generated SPAs"; }

    // J. Heading keyword stuffing
    preg_match_all('/<h[1-6][^>]*>(.*?)<\/h[1-6]>/is', $html, $headingMatches);
    $headingText  = strtolower(strip_tags(implode(' ', $headingMatches[1] ?? [])));
    $headingWords = array_filter(preg_split('/\s+/', $headingText), fn($w) => strlen($w) > 3);
    if (count($headingWords) > 5) {
        $wordCounts = array_count_values($headingWords);
        arsort($wordCounts);
        $topCount = reset($wordCounts);
        $topWord  = key($wordCounts);
        if ($topCount >= 3) { $score += 8; $reasons[] = "Heading keyword stuffing: \"$topWord\" repeated $topCount times — classic AI SEO content"; }
    }

    $score = max(0, min(100, $score));
    if (count($reasons) < 2)
        $reasons[] = $score < 35
            ? 'No major AI or builder fingerprints found — reads as organically written'
            : 'Multiple subtle signals collectively suggest automated or template-driven content';
    $reasons = array_slice($reasons, 0, 3);
    $verdict = $score >= 45 ? 'Likely AI' : 'Likely Human';
    return compact('score', 'verdict', 'reasons');
}

// ══════════════════════════════════════════════════════════════════════════════
// ROUTING
// ══════════════════════════════════════════════════════════════════════════════

// OPTIONS — CORS preflight
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: POST, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type');
    http_response_code(200);
    exit;
}

// POST (application/json) — JSON API used by React fetch()
$contentType = $_SERVER['CONTENT_TYPE'] ?? '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && str_contains($contentType, 'application/json')) {
    header('Content-Type: application/json');
    header('Access-Control-Allow-Origin: *');

    $input  = json_decode(file_get_contents('php://input'), true);
    $rawUrl = trim($input['url'] ?? '');

    if (empty($rawUrl))                             { http_response_code(400); echo json_encode(['error' => 'No URL provided']); exit; }
    if (!preg_match('#^https?://#i', $rawUrl))      $rawUrl = 'https://' . $rawUrl;
    if (!filter_var($rawUrl, FILTER_VALIDATE_URL))  { http_response_code(400); echo json_encode(['error' => 'Invalid URL']); exit; }

    $host = parse_url($rawUrl, PHP_URL_HOST);
    $ip   = gethostbyname($host);
    if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) === false) {
        http_response_code(403); echo json_encode(['error' => 'Private or reserved IP addresses are not allowed']); exit;
    }

    try {
        $html   = fetchHtml($rawUrl);
        $result = analyzeHtml($html, $AI_PHRASES, $BUILDER_SIGNATURES, $TAILWIND_UTILITY_PATTERNS, $AI_COMMENT_PATTERNS, $AI_SECTION_PATTERNS);
        echo json_encode($result);
    } catch (RuntimeException $e) { http_response_code(422); echo json_encode(['error' => $e->getMessage()]); }
    catch (Throwable $e)          { http_response_code(500); echo json_encode(['error' => 'Internal server error']); }
    exit;
}

// GET — HTML page. When ?url= is set, run analysis server-side for instant share links.
$shareUrl      = isset($_GET['url']) ? trim($_GET['url']) : '';
$preloadResult = null;
$preloadError  = null;

if (!empty($shareUrl)) {
    $raw = $shareUrl;
    if (!preg_match('#^https?://#i', $raw)) $raw = 'https://' . $raw;
    if (filter_var($raw, FILTER_VALIDATE_URL)) {
        $host = parse_url($raw, PHP_URL_HOST);
        $ip   = gethostbyname($host);
        if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE) !== false) {
            try {
                $fetched       = fetchHtml($raw);
                $preloadResult = analyzeHtml($fetched, $AI_PHRASES, $BUILDER_SIGNATURES, $TAILWIND_UTILITY_PATTERNS, $AI_COMMENT_PATTERNS, $AI_SECTION_PATTERNS);
            } catch (Throwable $e) { $preloadError = htmlspecialchars($e->getMessage()); }
        } else { $preloadError = 'Private or reserved IP addresses are not allowed'; }
    } else { $preloadError = 'Invalid URL'; }
}

$ogTitle = 'Vibe Checker — AI or Human?';
$ogDesc  = 'Detect whether a website was AI-generated or human-written using pattern analysis.';
if ($preloadResult) {
    $ogTitle = 'Vibe Check: ' . htmlspecialchars($shareUrl) . ' — ' . $preloadResult['verdict'] . ' (' . $preloadResult['score'] . '/100)';
    $ogDesc  = htmlspecialchars($preloadResult['reasons'][0] ?? $ogDesc);
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Vibe CHECKER — AI or Human?</title>

  <!-- Open Graph / Twitter share cards -->
  <meta property="og:title"        content="<?= $ogTitle ?>">
  <meta property="og:description"  content="<?= $ogDesc ?>">
  <meta property="og:type"         content="website">
  <meta name="twitter:card"        content="summary">
  <meta name="twitter:title"       content="<?= $ogTitle ?>">
  <meta name="twitter:description" content="<?= $ogDesc ?>">

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Orbitron:wght@400;700;900&display=swap" rel="stylesheet" />

  <style>
    /* ── Reset & Base ──────────────────────────────────────────────────────── */
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    :root {
      --bg:        #080c0a;
      --surface:   #0d1411;
      --border:    #1f3028;
      --amber:     #f0a500;
      --amber-dim: #7a5200;
      --green:     #39ff14;
      --red:       #ff3c3c;
      --text:      #c8d8c2;
      --muted:     #4a6050;
      --glow-a:    rgba(240,165,0,0.18);
      --glow-g:    rgba(57,255,20,0.15);
    }

    html, body {
      min-height: 100vh;
      background: var(--bg);
      color: var(--text);
      font-family: 'Share Tech Mono', monospace;
      overflow-x: hidden;
    }

    /* ── Scanline overlay ──────────────────────────────────────────────────── */
    body::before {
      content: '';
      position: fixed; inset: 0;
      background: repeating-linear-gradient(
        0deg,
        transparent,
        transparent 2px,
        rgba(0,0,0,0.07) 2px,
        rgba(0,0,0,0.07) 4px
      );
      pointer-events: none;
      z-index: 9999;
    }

    /* ── CRT vignette ──────────────────────────────────────────────────────── */
    body::after {
      content: '';
      position: fixed; inset: 0;
      background: radial-gradient(ellipse at center, transparent 55%, rgba(0,0,0,0.65) 100%);
      pointer-events: none;
      z-index: 9998;
    }

    /* ── Grid background ───────────────────────────────────────────────────── */
    .grid-bg {
      position: fixed; inset: 0;
      background-image:
        linear-gradient(rgba(31,48,40,0.4) 1px, transparent 1px),
        linear-gradient(90deg, rgba(31,48,40,0.4) 1px, transparent 1px);
      background-size: 40px 40px;
      z-index: 0;
    }

    /* ── Layout ────────────────────────────────────────────────────────────── */
    #root {
      position: relative;
      z-index: 1;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 2rem 1rem;
    }

    /* ── Header ────────────────────────────────────────────────────────────── */
    .header {
      text-align: center;
      margin-bottom: 2.5rem;
    }

    .header-eyebrow {
      font-family: 'Share Tech Mono', monospace;
      font-size: 0.7rem;
      letter-spacing: 0.35em;
      color: var(--amber);
      text-transform: uppercase;
      margin-bottom: 0.5rem;
      opacity: 0.8;
    }

    .header-title {
      font-family: 'Orbitron', sans-serif;
      font-size: clamp(2.2rem, 6vw, 3.8rem);
      font-weight: 900;
      letter-spacing: 0.08em;
      color: var(--amber);
      text-shadow:
        0 0 20px rgba(240,165,0,0.6),
        0 0 60px rgba(240,165,0,0.25);
      line-height: 1;
    }

    .header-sub {
      margin-top: 0.75rem;
      font-size: 0.78rem;
      color: var(--muted);
      letter-spacing: 0.1em;
    }

    /* ── Card ──────────────────────────────────────────────────────────────── */
    .card {
      width: 100%;
      max-width: 640px;
      background: var(--surface);
      border: 1px solid var(--border);
      box-shadow:
        0 0 0 1px rgba(240,165,0,0.05),
        0 0 40px rgba(0,0,0,0.6),
        inset 0 1px 0 rgba(240,165,0,0.06);
      position: relative;
      overflow: hidden;
    }

    .card::before {
      content: '';
      display: block;
      height: 2px;
      background: linear-gradient(90deg, transparent, var(--amber), transparent);
    }

    .card-inner { padding: 2rem 2rem 2.5rem; }

    /* ── Input group ───────────────────────────────────────────────────────── */
    .input-label {
      display: block;
      font-size: 0.65rem;
      letter-spacing: 0.3em;
      color: var(--amber-dim);
      text-transform: uppercase;
      margin-bottom: 0.5rem;
    }

    .input-row { display: flex; gap: 0.6rem; }

    .url-input {
      flex: 1;
      background: #050807;
      border: 1px solid var(--border);
      color: var(--green);
      font-family: 'Share Tech Mono', monospace;
      font-size: 0.88rem;
      padding: 0.75rem 1rem;
      outline: none;
      transition: border-color 0.2s, box-shadow 0.2s;
      caret-color: var(--green);
    }

    .url-input::placeholder { color: var(--muted); }

    .url-input:focus {
      border-color: var(--amber-dim);
      box-shadow: 0 0 0 1px rgba(240,165,0,0.15), 0 0 12px rgba(240,165,0,0.08);
    }

    .btn {
      background: var(--amber);
      color: #050807;
      font-family: 'Orbitron', sans-serif;
      font-size: 0.7rem;
      font-weight: 700;
      letter-spacing: 0.12em;
      text-transform: uppercase;
      padding: 0.75rem 1.2rem;
      border: none;
      cursor: pointer;
      white-space: nowrap;
      transition: background 0.15s, box-shadow 0.15s, transform 0.1s;
    }

    .btn:hover:not(:disabled) { background: #ffc733; box-shadow: 0 0 16px rgba(240,165,0,0.4); }
    .btn:active:not(:disabled) { transform: scale(0.97); }
    .btn:disabled { background: var(--amber-dim); cursor: not-allowed; opacity: 0.6; }

    /* ── Error ─────────────────────────────────────────────────────────────── */
    .error-bar {
      margin-top: 1rem;
      padding: 0.65rem 1rem;
      background: rgba(255,60,60,0.08);
      border: 1px solid rgba(255,60,60,0.25);
      color: var(--red);
      font-size: 0.78rem;
      letter-spacing: 0.05em;
    }
    .error-bar::before { content: '✕ ERROR: '; opacity: 0.7; }

    /* ── Spinner ───────────────────────────────────────────────────────────── */
    .loading-block {
      margin-top: 2rem;
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 1.2rem;
    }

    .scanner-line-wrap {
      width: 100%;
      height: 2px;
      background: var(--border);
      position: relative;
      overflow: hidden;
    }

    .scanner-line {
      position: absolute;
      top: 0; left: -40%;
      width: 40%;
      height: 100%;
      background: linear-gradient(90deg, transparent, var(--amber), transparent);
      animation: scan 1.2s linear infinite;
    }

    @keyframes scan { from { left: -40%; } to { left: 110%; } }

    .loading-text {
      font-size: 0.7rem;
      letter-spacing: 0.3em;
      color: var(--amber-dim);
      animation: blink 1.1s step-start infinite;
    }
    @keyframes blink { 50% { opacity: 0.2; } }

    /* ── Results ───────────────────────────────────────────────────────────── */
    .results { margin-top: 2.2rem; animation: fadeIn 0.5s ease; }

    @keyframes fadeIn { from { opacity: 0; transform: translateY(8px); } to { opacity: 1; transform: translateY(0); } }

    .divider {
      height: 1px;
      background: linear-gradient(90deg, transparent, var(--border), transparent);
      margin-bottom: 2rem;
    }

    .score-row {
      display: flex;
      align-items: flex-end;
      justify-content: space-between;
      margin-bottom: 1.2rem;
    }

    .score-number {
      font-family: 'Orbitron', sans-serif;
      font-size: clamp(3.5rem, 12vw, 5.5rem);
      font-weight: 900;
      line-height: 1;
      letter-spacing: -0.02em;
      transition: color 0.5s, text-shadow 0.5s;
    }
    .score-number.ai    { color: var(--red);   text-shadow: 0 0 30px rgba(255,60,60,0.5), 0 0 80px rgba(255,60,60,0.15); }
    .score-number.human { color: var(--green);  text-shadow: 0 0 30px rgba(57,255,20,0.5), 0 0 80px rgba(57,255,20,0.15); }

    .verdict-badge {
      font-family: 'Orbitron', sans-serif;
      font-size: 0.75rem;
      font-weight: 700;
      letter-spacing: 0.15em;
      padding: 0.4rem 0.9rem;
      border: 1px solid;
      text-transform: uppercase;
      margin-bottom: 0.5rem;
    }
    .verdict-badge.ai    { color: var(--red);   border-color: rgba(255,60,60,0.4); background: rgba(255,60,60,0.07); }
    .verdict-badge.human { color: var(--green);  border-color: rgba(57,255,20,0.4); background: rgba(57,255,20,0.07); }

    .progress-track {
      height: 6px;
      background: #0a100d;
      border: 1px solid var(--border);
      overflow: hidden;
      margin-bottom: 2rem;
      position: relative;
    }
    .progress-fill {
      height: 100%;
      transition: width 1s cubic-bezier(0.22,1,0.36,1);
      position: relative;
    }
    .progress-fill::after {
      content: '';
      position: absolute;
      right: 0; top: 0; bottom: 0;
      width: 6px;
      background: inherit;
      filter: blur(4px) brightness(2);
    }
    .progress-fill.ai    { background: var(--red); }
    .progress-fill.human { background: var(--green); }

    .progress-ticks { display: flex; justify-content: space-between; margin-top: 0.3rem; margin-bottom: 1.8rem; }
    .progress-tick  { font-size: 0.6rem; color: var(--muted); letter-spacing: 0.05em; }

    .reasons-label {
      font-size: 0.62rem;
      letter-spacing: 0.3em;
      color: var(--amber-dim);
      text-transform: uppercase;
      margin-bottom: 0.8rem;
    }

    .reason-item {
      display: flex;
      gap: 0.75rem;
      padding: 0.75rem 0;
      border-bottom: 1px solid var(--border);
      font-size: 0.82rem;
      line-height: 1.55;
      color: var(--text);
      align-items: flex-start;
      animation: fadeIn 0.4s ease both;
    }
    .reason-item:last-child { border-bottom: none; }
    .reason-bullet { color: var(--amber); font-size: 0.75rem; margin-top: 0.1rem; flex-shrink: 0; }

    /* ── Share row (new) ───────────────────────────────────────────────────── */
    .share-row {
      display: flex;
      gap: 0.6rem;
      margin-top: 1.6rem;
      padding-top: 1.4rem;
      border-top: 1px solid var(--border);
      flex-wrap: wrap;
    }

    .share-btn {
      display: flex;
      align-items: center;
      gap: 0.45rem;
      background: transparent;
      border: 1px solid var(--border);
      color: var(--muted);
      font-family: 'Share Tech Mono', monospace;
      font-size: 0.65rem;
      letter-spacing: 0.18em;
      text-transform: uppercase;
      padding: 0.5rem 0.9rem;
      cursor: pointer;
      transition: border-color 0.15s, color 0.15s, box-shadow 0.15s;
      white-space: nowrap;
    }
    .share-btn:hover {
      border-color: var(--amber-dim);
      color: var(--amber);
      box-shadow: 0 0 10px rgba(240,165,0,0.12);
    }
    .share-btn:active { transform: scale(0.97); }
    .share-btn svg {
      width: 12px; height: 12px;
      fill: none; stroke: currentColor;
      stroke-width: 1.8; stroke-linecap: round; stroke-linejoin: round;
      flex-shrink: 0;
    }

    /* ── Toast (new) ───────────────────────────────────────────────────────── */
    #vc-toast {
      position: fixed;
      bottom: 2rem;
      left: 50%;
      transform: translateX(-50%) translateY(12px);
      background: var(--surface);
      border: 1px solid var(--amber-dim);
      color: var(--amber);
      font-family: 'Share Tech Mono', monospace;
      font-size: 0.68rem;
      letter-spacing: 0.2em;
      text-transform: uppercase;
      padding: 0.55rem 1.3rem;
      opacity: 0;
      pointer-events: none;
      transition: opacity 0.2s, transform 0.2s;
      z-index: 10000;
      white-space: nowrap;
    }
    #vc-toast.show { opacity: 1; transform: translateX(-50%) translateY(0); }

    /* ── Footer ────────────────────────────────────────────────────────────── */
    .footer {
      margin-top: 1.8rem;
      font-size: 0.62rem;
      color: var(--muted);
      letter-spacing: 0.12em;
      text-align: center;
    }

    /* ── Responsive ────────────────────────────────────────────────────────── */
    @media (max-width: 480px) {
      .card-inner { padding: 1.5rem 1.2rem 2rem; }
      .input-row  { flex-direction: column; }
      .btn        { width: 100%; text-align: center; }
    }
  </style>
</head>
<body>
  <div class="grid-bg"></div>
  <div id="root"></div>
  <div id="vc-toast"></div>

  <!-- React + Babel CDN -->
  <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
  <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
  <!-- html2canvas for image export -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>

  <!-- PHP → JS bridge: server-side preloaded result for ?url= share links -->
  <script>
    window.__VC_PRELOAD__       = <?= $preloadResult ? json_encode(['url' => $shareUrl, 'result' => $preloadResult]) : 'null' ?>;
    window.__VC_PRELOAD_ERROR__ = <?= $preloadError  ? json_encode($preloadError) : 'null' ?>;
  </script>

  <script type="text/babel">
    const { useState, useEffect, useRef, useCallback } = React;

    /* ── Toast helper ─────────────────────────────────────────────────────── */
    function showToast(msg, ms = 2200) {
      const el = document.getElementById('vc-toast');
      el.textContent = msg;
      el.classList.add('show');
      clearTimeout(el._t);
      el._t = setTimeout(() => el.classList.remove('show'), ms);
    }

    /* ── Animated score counter ───────────────────────────────────────────── */
    function useCountUp(target, duration = 1000) {
      const [display, setDisplay] = useState(0);
      const frame = useRef(null);

      useEffect(() => {
        if (target === null) { setDisplay(0); return; }
        const start = performance.now();
        const step  = (now) => {
          const elapsed  = now - start;
          const progress = Math.min(elapsed / duration, 1);
          const eased    = 1 - Math.pow(1 - progress, 3);
          setDisplay(Math.round(target * eased));
          if (progress < 1) frame.current = requestAnimationFrame(step);
        };
        frame.current = requestAnimationFrame(step);
        return () => cancelAnimationFrame(frame.current);
      }, [target]);

      return display;
    }

    /* ── Progress bar ─────────────────────────────────────────────────────── */
    function ProgressBar({ score, cls }) {
      const [width, setWidth] = useState(0);
      useEffect(() => {
        const t = setTimeout(() => setWidth(score), 80);
        return () => clearTimeout(t);
      }, [score]);

      return (
        <>
          <div className="progress-track">
            <div className={`progress-fill ${cls}`} style={{ width: `${width}%` }} />
          </div>
          <div className="progress-ticks">
            <span className="progress-tick">0% HUMAN</span>
            <span className="progress-tick">50%</span>
            <span className="progress-tick">AI 100%</span>
          </div>
        </>
      );
    }

    /* ── Spinner ──────────────────────────────────────────────────────────── */
    function Spinner() {
      const msgs = ['FETCHING HTML...','SCANNING PHRASES...','ANALYZING PATTERNS...','COMPUTING SCORE...'];
      const [msgIdx, setMsgIdx] = useState(0);
      useEffect(() => {
        const iv = setInterval(() => setMsgIdx(i => (i + 1) % msgs.length), 1100);
        return () => clearInterval(iv);
      }, []);
      return (
        <div className="loading-block">
          <div className="scanner-line-wrap"><div className="scanner-line" /></div>
          <div className="loading-text">{msgs[msgIdx]}</div>
        </div>
      );
    }

    /* ── Share row ────────────────────────────────────────────────────────── */
    function ShareRow({ analyzedUrl, cardRef }) {
      /* Copy shareable ?url= link */
      const handleCopyLink = useCallback(() => {
        const link = window.location.origin + window.location.pathname
          + '?url=' + encodeURIComponent(analyzedUrl);
        if (navigator.clipboard?.writeText) {
          navigator.clipboard.writeText(link).then(() => showToast('✓ LINK COPIED'));
        } else {
          const ta = Object.assign(document.createElement('textarea'), {
            value: link, style: 'position:fixed;opacity:0'
          });
          document.body.appendChild(ta);
          ta.select();
          try   { document.execCommand('copy'); showToast('✓ LINK COPIED'); }
          catch { showToast('✕ COPY FAILED'); }
          ta.remove();
        }
      }, [analyzedUrl]);

      /* Save card as PNG via html2canvas */
      const handleSaveImage = useCallback(async () => {
        if (!cardRef.current) return;
        showToast('RENDERING...', 4000);
        try {
          const canvas = await html2canvas(cardRef.current, {
            backgroundColor: '#0d1411',
            scale: 2,
            useCORS: true,
            logging: false,
            ignoreElements: el => el.classList?.contains('share-row'),
          });
          const a = document.createElement('a');
          a.download = 'vibecheck_' + analyzedUrl.replace(/[^a-z0-9]/gi, '_').slice(0, 40) + '.png';
          a.href = canvas.toDataURL('image/png');
          a.click();
          showToast('✓ IMAGE SAVED');
        } catch { showToast('✕ RENDER FAILED'); }
      }, [cardRef]);

      /* New scan — wipe result and clean URL */
      const handleNewScan = useCallback(() => {
        history.pushState({}, '', window.location.pathname);
        window.__VC_FORCE_RESET__?.();
      }, []);

      return (
        <div className="share-row">
          <button className="share-btn" onClick={handleCopyLink} title="Copy shareable link">
            <svg viewBox="0 0 24 24"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>
            Copy Link
          </button>
          <button className="share-btn" onClick={handleSaveImage} title="Save result as image">
            <svg viewBox="0 0 24 24"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
            Save Image
          </button>
          <button className="share-btn" onClick={handleNewScan} title="Check another URL">
            <svg viewBox="0 0 24 24"><polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/></svg>
            New Scan
          </button>
        </div>
      );
    }

    /* ── Results ──────────────────────────────────────────────────────────── */
    function Results({ data, analyzedUrl, cardRef }) {
      const { score, verdict, reasons } = data;
      const cls       = verdict === 'Likely AI' ? 'ai' : 'human';
      const displayed = useCountUp(score, 900);

      return (
        <div className="results">
          <div className="divider" />
          <div className="score-row">
            <div className={`score-number ${cls}`}>
              {displayed}<span style={{ fontSize: '40%', opacity: 0.6 }}>%</span>
            </div>
            <div className={`verdict-badge ${cls}`}>{verdict}</div>
          </div>

          <ProgressBar score={score} cls={cls} />

          <div className="reasons-label">▸ ANALYSIS OUTPUT</div>
          {reasons.map((r, i) => (
            <div className="reason-item" key={i} style={{ animationDelay: `${i * 0.12}s` }}>
              <span className="reason-bullet">◆</span>
              <span>{r}</span>
            </div>
          ))}

          <ShareRow analyzedUrl={analyzedUrl} cardRef={cardRef} />
        </div>
      );
    }

    /* ── Main App ─────────────────────────────────────────────────────────── */
    function App() {
      const [url,      setUrl]      = useState('');
      const [loading,  setLoading]  = useState(false);
      const [result,   setResult]   = useState(null);
      const [error,    setError]    = useState('');
      const [analyzed, setAnalyzed] = useState('');
      const cardRef = useRef(null);

      /* Expose reset for ShareRow's "New Scan" button */
      window.__VC_FORCE_RESET__ = () => {
        setUrl(''); setResult(null); setError(''); setAnalyzed('');
      };

      /* Auto-run from PHP-injected preload (shareable ?url= link) */
      useEffect(() => {
        if (window.__VC_PRELOAD__) {
          const { url: preUrl, result: preResult } = window.__VC_PRELOAD__;
          setUrl(preUrl);
          setAnalyzed(preUrl);
          setResult(preResult);
          window.__VC_PRELOAD__ = null;
        } else if (window.__VC_PRELOAD_ERROR__) {
          setError(window.__VC_PRELOAD_ERROR__);
          window.__VC_PRELOAD_ERROR__ = null;
        }
      }, []);

      const handleCheck = async () => {
        if (!url.trim()) return;
        setLoading(true);
        setResult(null);
        setError('');
        setAnalyzed('');

        try {
          const res  = await fetch(window.location.pathname, {
            method:  'POST',
            headers: { 'Content-Type': 'application/json' },
            body:    JSON.stringify({ url: url.trim() }),
          });
          const data = await res.json();
          if (!res.ok || data.error) throw new Error(data.error || `HTTP ${res.status}`);
          setAnalyzed(url.trim());
          setResult(data);
        } catch (e) {
          setError(e.message || 'Could not reach the server');
        } finally {
          setLoading(false);
        }
      };

      const handleKey = (e) => { if (e.key === 'Enter' && !loading) handleCheck(); };

      return (
        <>
          <div className="header">
            <div className="header-eyebrow">◈ Diagnostic System v1.0</div>
            <div className="header-title">VIBE CHECKER</div>
            <div className="header-sub">
              AI-generated or human-written? Enter a URL to find out.
            </div>
          </div>

          <div className="card" ref={cardRef}>
            <div className="card-inner">
              <label className="input-label" htmlFor="url-input">▸ TARGET URL</label>
              <div className="input-row">
                <input
                  id="url-input"
                  className="url-input"
                  type="url"
                  value={url}
                  placeholder="https://example.com"
                  onChange={(e) => setUrl(e.target.value)}
                  onKeyDown={handleKey}
                  disabled={loading}
                  autoComplete="off"
                  spellCheck="false"
                />
                <button className="btn" onClick={handleCheck} disabled={loading || !url.trim()}>
                  {loading ? '...' : 'CHECK VIBE'}
                </button>
              </div>

              {error && <div className="error-bar">{error}</div>}
              {loading && <Spinner />}
              {result && !loading && (
                <Results data={result} analyzedUrl={analyzed} cardRef={cardRef} />
              )}
            </div>
          </div>

          <div className="footer">
            VIBE CHECKER — PATTERN ANALYSIS ENGINE &nbsp;|&nbsp; NO DATA STORED
          </div>
        </>
      );
    }

    ReactDOM.createRoot(document.getElementById('root')).render(<App />);
  </script>
</body>
</html>
